name: 'CI/CD'
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  bun:
    name: Install dependencies (bun)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.3.6'
          cache: 'bun'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate README.md File
        run: bun prettier

  prettier:
    name: check linting (prettier)
    needs: [bun]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.3.6'
          cache: 'bun'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check prettier
        run: bun prettier:check

  eslint:
    name: check linting (eslint)
    needs: [bun]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.3.6'
          cache: 'bun'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check eslint
        run: bun eslint:check

  build:
    name: check building
    needs: [bun, eslint]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.3.6'
          cache: 'bun'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check building
        run: bun run build
